### ISSUE TITLE
Register with Unity?

### ISSUE THREAD

**Issue by cosmoKenney** [neosmart/AspSqliteCache#11]
I need to register the Sqlite Cache within a IUnityContainer any clue how this would be done?

**Comment by cosmoKenney** [comment]
This is what I have. Testing now.  What are the default values for `SqliteCacheOptions.CleanupInterval` and `SqliteCacheOptions.MemoryOnly`?

```
			var tmpPath = Path.GetTempPath();
			tmpPath = Path.Combine(tmpPath, "ProvPubs.Compline.Web.cache");

			SqliteCacheOptions options = new SqliteCacheOptions {
				CachePath = tmpPath				
			};

			SqliteCache cache = new SqliteCache(options, null);
			container.RegisterInstance(cache);
```

**Comment by cosmoKenney** [comment]
The above is not working. I'm running this on .net 4.8. When I try to create the SqliteCache instance it throws:
```
Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) C:\Users\khadd\AppData\Local\Temp\Temporary ASP.NET Files\vs\42893e7c\fbb585\assembly\dl3\daa50941\00d2f265_30cbd701\runtimes\win-x64\native\e_sqlite3.dll
    2) C:\Users\khadd\AppData\Local\Temp\Temporary ASP.NET Files\vs\42893e7c\fbb585\assembly\dl3\daa50941\00d2f265_30cbd701\e_sqlite3.dll
win TryLoad: C:\Users\khadd\AppData\Local\Temp\Temporary ASP.NET Files\vs\42893e7c\fbb585\assembly\dl3\daa50941\00d2f265_30cbd701\runtimes\win-x64\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: C:\Users\khadd\AppData\Local\Temp\Temporary ASP.NET Files\vs\42893e7c\fbb585\assembly\dl3\daa50941\00d2f265_30cbd701\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND
```

**Comment by mqudsi** [comment]
Add a dependency on [the right SQLite PCL nuget package](https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3/) for your platform then call `SQLitePCL.Batteries_V2.Init();` at startup (before doing anything related to SqliteCache).

See https://github.com/ericsink/SQLitePCL.raw for more.

**Comment by mqudsi** [comment]
Are you using nuget? How did you add a dependency to SqliteCache? The same way you did that.

**Comment by cosmoKenney** [comment]
> Are you using nuget? How did you add a dependency to SqliteCache? The same way you did that.

Yes. All I did was add the SqliteCache package via the VS 2019 nuget UI. This is also what I did in my .net core project (unless I'm forgetting some extra steps) and it worked fine.

**Comment by mqudsi** [comment]
I'm not familiar with Unity, but you'll need to add a dependency for `SQLitePCLRaw.bundle_e_sqlite3` and call that stub before using sqlitecache.
