### ISSUE TITLE
Bug when using with sqlite library that is compiled with SQLITE_DSQ=0

### ISSUE THREAD

**Issue by Blackclaws** [neosmart/AspSqliteCache#12]
Sqlite has the oddity that it treats double quoted strings that don't evaluate to an identifier as strings. This is _not_ sql standard behavior. Since in the initialization routine values are inserted into the meta table that contain strings that are double quoted. Those will fail with a rather cryptic message 'created is not a column name' when the underlying sqlite does not support this odd configuration option.

Since its recommended to compile sqlite with DSQ=0 (i.e. always treat double quotes as identifiers) it would be nice if this could be reflected in the sql statements by replacing double quoted strings by single quoted strings.

**Comment by mqudsi** [comment]
Thanks for pointing this out. I'll put out a release with this fix shortly.

**Comment by mqudsi** [comment]
Hi @Blackclaws 

Sorry for the delay but I just pushed out a commit that should fix this and will be making a final 6.x release with this fix soon. Are you able to test this?

I can compile SQLite with `SQLITE_DSQ=0` but I'm not sure how you were actually using your copy of the SQLite library? The nuget has a dependency on `SQLitePCLRaw.bundle_green` which ships with its own copy of the SQLite library on all supported platforms - how did you bypass that?

**Comment by mqudsi** [comment]
To make it easier to test, I published the latest build with these changes on nuget as NeoSmart.Cache.SqliteCache version 6.1.0-preview1.

**Comment by Blackclaws** [comment]
> Hi @Blackclaws
> 
> Sorry for the delay but I just pushed out a commit that should fix this and will be making a final 6.x release with this fix soon. Are you able to test this?
> 
> I can compile SQLite with `SQLITE_DSQ=0` but I'm not sure how you were actually using your copy of the SQLite library? The nuget has a dependency on `SQLitePCLRaw.bundle_green` which ships with its own copy of the SQLite library on all supported platforms - how did you bypass that? Are you including this package with private assets set to true then using your own SQLite backfill?

I bypassed it by compiling the library myself excluding bundle_green.  We're using the cache on Android via Unity where bundle_green doesn't work. In general I'm not sure if forcing this specific version is in general a good idea.

Basically what I did was remove bundle_green and manually linked against sqlite:
```
        SQLitePCL.raw.SetProvider(new SQLite3Provider_sqlite3());
 ```

**Comment by Blackclaws** [comment]
I personally think that removing the explicit dependency on bundle_green makes sense given that its not the only way you can use SQLitePCLRaw and it restricts the user in what they _can_ use. The correct dependency should be SQLitePCLRaw.core and a section in the docs under installation basically telling the user to go ahead and install one of the providers and initialize it should be fine as well? You could also split it into two packages, where one is the core cache without the dependency and the other one keeps the original name including the dependency (not breaking backwards compatibility).

The problem is that bundle_green itself ships with a couple of libraries that I'd rather like to avoid pulling into the project in the first place as they are unnecessary ballast (they don't work on iOS or Android anyway, at least not in the context we are in).
