### ISSUE TITLE
Runtime exception after updating to .net7/EF7

### ISSUE THREAD

**Issue by Msurrow** [neosmart/AspSqliteCache#14]
See PR #13  
I started getting a runtime exception in my project after updating it (and references library projects) to net7/EF7. 

The exception I start getting is:
```
System.Exception: Could not resolve a service of type 'Microsoft.Extensions.Caching.Distributed.IDistributedCache' for the parameter 'cache' of method 'Configure' on type 'MyApi.Startup'.
---> System.TypeInitializationException: The type initializer for 'NeoSmart.Caching.Sqlite.SqliteCache' threw an exception.
---> System.TypeLoadException: Method 'sqlite3_load_extension' in type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=2.0.7.1395, Culture=neutral, PublicKeyToken=9c301db686d0bd12' does not have an implementation.
```

From what I understand this happens if you have a project containing an interface (`Microsoft.Extensions.Caching.Distributed.IDistributedCache`), and another project containing an implementation of this interface (`NeoSmart.Caching.Sqlite.SqliteCache`) and a project using the implementation. If the using-project is build with an other version of the interface-project dll then the implementing-project is, then the exception happens. Solutions are said to be clean everything (e.g. delete bin) and rebuild, but the problem is I can't rebuild the NeoSmart.Caching.Sqlite package, and my project is referencing another project that depends on Microsoft.Data.Sqlite.Core 7.0.2 which I'm guessing is where the conflict is, since NeoSmart.Caching.Sqlite package is depending on Microsoft.Data.Sqlite.Core 6.0.1

I created a PR with the package updates which hopefully solves this issue.

Edit: Well, maybe the above isn't exactly right. I did a bit more digging and found https://github.com/ericsink/SQLitePCL.raw/issues/229 - and its more complicated than I have time to get into now unfortunately. However, I did confirm that my issue when away if I remove the reference to my library project which depends on Microsoft.Data.Sqlite.Core 7.0.2. So, there seems to be some conflict when 7 is introduced - and hopefully a dep version update solves it.

**Comment by mqudsi** [comment]
Yeah, I was going to comment and write that I don't think it's necessarily the v7 change that's the problem since I'm using this in ASP.NET 7 projects without an issue.

I'll look into this some more and probably push out a v7 update in all cases (though I don't think we need to add a separate net7 target, just up the dependencies). However I would push out the clear cache PR first so we can get that in v6 before pushing out any v7.

**Comment by mqudsi** [comment]
I've pushed some dependency upgrades to master that might take care of your issue without rebasing against .NET 7/ASP.NET Core 7. Can you please try?

**Comment by mqudsi** [comment]
To make it easier to test, I published the latest build with these changes on nuget as NeoSmart.Cache.SqliteCache version 6.1.0-preview1.

**Comment by Msurrow** [comment]
Thank you for this. I've updated our projects to use the 6.1.0-preview1 and the issue is now gone.
