### ISSUE TITLE
Sqlite in WAL mode vs. use as actual distributed cache

### ISSUE THREAD

**Issue by IcoDeveloper** [neosmart/AspSqliteCache#16]
From SQLite documentation on [WAL Mode:](https://www.sqlite.org/wal.html): 

"All processes using a database must be on the same host computer; WAL does not work over a network filesystem."

This seems to effectively block the scenario of using AspSqliteCache as an actual distrubuted cache; otherwise it would seem to be usable as a low volume distributed cache with just two or three nodes.
While the focus in documentation is the persistence part of the cache, not the distributed part it wld be interesting to see if limited distribution is actually possible and if/what changes are required to make that feasible.

**Comment by mqudsi** [comment]
We make certain other design choices in the name of optimizing single-node performance that would preclude the use of the database by multiple nodes at the same time. While it's certainly possible, actual distributed usage of this library is outside the intended scope and I would recommend using Redis instead.
