### ISSUE TITLE
Adding bulkinsert support

### ISSUE THREAD

**Issue by Rap22tor** [neosmart/AspSqliteCache#3]
Hi

I've recently run into a problem where I have to insert a large list of objects/keys into the cache database. Using the existing Set and SetAsync methods, this obviously ran pretty slowly. I now have added a SetBulkAsync method, which reduces the time consumed significantly. In my case, it improved a process that took around ~25 mins to about 25 seconds.
This method takes in a IEnumerable of KeyValuePairs and produces a single Sqlite query. This query is then executed just like in SetAsync. In my program I can now seperate my list into smaller chunks and use SetBulkAsync to insert them pretty quickly. 

I hope this is useful for others too. Let me know if you prefer the solution any different, I'll gladly adapt.

Thanks for this library!
Elias

**Comment by Rap22tor** [comment]
Hi, thanks for the quick reply

I had indeed been using an older version of the package. I updated the times did drop significantly. Though I was still able to measure around a 3x improvement with my method (1 minutes and 7 seconds vs 22 seconds). I used the System.Diagnostics.Stopwatch to measure and the dataset was the same (about 90k objects). 
Although my problem would be basically fixed with the new version, could a bulk insert still be of use?

**Comment by gutzi** [comment]
I would want the changes.

**Comment by mqudsi** [comment]
@gutzi  can you provide some information about what you'd use this for/how you were previously bottlenecked without it?

---

I've just released [5.0-preview3 on nuget](https://www.nuget.org/packages/NeoSmart.Caching.Sqlite/5.0.0-preview3) 
 that includes this feature, among others. @Rap22tor: you're named in the changelog, let me know if you prefer the credit worded differently.

**Comment by Rap22tor** [comment]
Awesome, thank you!
