### ISSUE TITLE
Convert `AbsoluteExpiration` to UTC if it isn't already

### ISSUE THREAD

**Issue by ravindUwU** [neosmart/AspSqliteCache#5]
Hi @mqudsi 👋!

Given how `DateTimeOffset.Ticks` depends on `DateTimeOffset.Offset`, and `RemoveExpires` compares persisted expiry dates with `DateTimeOffset.UtcNow.Ticks`,

https://github.com/neosmart/AspSqliteCache/blob/a35868f1a09429a3fd8ea207013cec5dbbeb90fe/SqliteCache/SqliteCache.cs#L462-L467

...shouldn't `AbsoluteExpiration` be converted to UTC via `DateTimeOffset.ToUniversalTime`, when entries are persisted? 🤔

https://github.com/neosmart/AspSqliteCache/blob/a35868f1a09429a3fd8ea207013cec5dbbeb90fe/SqliteCache/SqliteCache.cs#L405-L426

**Comment by mqudsi** [comment]
Hello @ravindUwU 👋!

Thanks for stopping by and opening this issue. I believe you are correct; all other values that are assigned to `expiry` have their UTC values stored except `options.AbsoluteExpiration.Value` which is used as-is.

Do you want to open a pull request w/ the patch?

**Comment by ravindUwU** [comment]
Yup! I'll submit a PR shortly. Thanks, @mqudsi! 😇

**Comment by ravindUwU** [comment]
Hi @mqudsi, could this fix be released on NuGet? Thanks! 😅

**Comment by mqudsi** [comment]
lol, yes, that is kind of important. We can definitely do that!

**Comment by mqudsi** [comment]
This is available on Nuget in both 5.0.2 and 6.0.1 (depending on the version of .NET you are targeting). Thanks for your contribution, you have been named in the official release notes!
